<a href="https://colab.research.google.com/github/amandarcrangel/project_studies_fiap/blob/main/import_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

vendas = pd.read_parquet ("vendas_zoop_bronze.parquet")
estoques = pd.read_parquet ("estoques_zoop_bronze.parquet")
redes_sociais = pd.read_parquet ("redes_sociais_zoop_bronze.parquet")

In [ ]:
vendas.head()

,ID_venda,Dia,Mês,Ano,Horario,Canal_venda,Origem_venda,ID_produto,Produto,Categoria_produto,...,Quantidade,Metodo_pagamento,ID_cliente,Nome_cliente,Genero_cliente,Idade_cliente,Cidade_cliente,UF_cliente,Regiao_cliente,Avaliacao
0,0,20,8,2021,08:58:00,Loja 2,Loja,3,Cafeteira,Eletrodomésticos,...,3,Cartão de débito,21,Manuella Pereira,Feminino,28,Campo Grande,Mato Grosso do Sul,Centro-Oeste,4
1,1,20,8,2021,11:32:00,Loja 1,Loja,14,Impressora,Eletrônicos,...,1,Dinheiro,218,Maria Sophia Rios,Feminino,40,Uberlândia,Minas Gerais,Sudeste,3
2,2,20,8,2021,13:19:00,Loja 1,Loja,29,Máquina de café,Eletrodomésticos,...,2,Cartão de crédito,277,Ana Sophia Marques,Feminino,34,Campinas,São Paulo,Sudeste,5
3,3,20,8,2021,13:42:00,Loja 2,Loja,3,Cafeteira,Eletrodomésticos,...,1,PIX,282,Clara Rezende,Feminino,39,São Gonçalo,Rio de Janeiro,Sudeste,3
4,4,20,8,2021,14:49:00,Loja 1,Loja,8,Micro-ondas,Eletrodomésticos,...,1,Cartão de débito,295,Thiago Lima,Masculino,59,Foz do Iguaçu,Paraná,Sul,2

In [ ]:
estoques.head()

,ID_estoque,ID_produto,Produto,Categoria_produto,Data,Horario,Quantidade_em_estoque,Quantidade_novos_produtos,Quantidade_vendida
0,0,0,"Smart_TV_55""",Eletrônicos,2021/07/01,21:45:00,100,20,0
1,1,1,Frigobar,Eletrodomésticos,2021/07/01,20:13:00,100,29,0
2,2,2,Ventilador_de_teto,Eletrodomésticos,2021/07/01,13:30:00,100,16,0
3,3,3,Cafeteira,Eletrodomésticos,2021/07/01,06:20:00,100,10,0
4,4,4,Smartphone,Eletrônicos,2021/07/01,14:33:00,100,49,0

In [ ]:
pd.set_option('display.max_columns', 100)
redes_sociais.head()

,ID_social,Data,Influencia_autor,Plataforma,Nome_produto,Categoria_produto,Comentario
0,0,2021-09-07,7864,X (Twitter),Cafeteira,Eletrodomésticos,Estou impressionado com a qualidade e a eficiê...
1,1,2021-09-30,60503,X (Twitter),Impressora,Eletrônicos,"Produto ok, mas achei o preço um pouco elevado..."
2,2,2021-09-19,86828,X (Twitter),Máquina de café,Eletrodomésticos,Produto incrível! Desempenho muito acima da mé...
3,3,2021-09-19,28615,X (Twitter),Cafeteira,Eletrodomésticos,"Produto bom, mas nada excepcional. #Cafeteira ..."
4,4,2021-09-12,38424,Facebook,Micro-ondas,Eletrodomésticos,Produto ruim. Esperava muito mais. #Micro-onda...