<a href="https://colab.research.google.com/github/amandarcrangel/project_studies_fiap/blob/main/Teste_Hip%C3%B3tese.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Teste de Hipótese

In [ ]:
# instalar versão atualizada
! sudo pip install scipy==1.7.1
# instalar nova ferramenta para testes de hipoteses
! sudo pip install pingouin

ERROR: Ignored the following yanked versions: 1.11.0, 1.14.0rc1
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement scipy==1.7.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1, 1.14.0rc2, 1.14.0, 1.14.1, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2)
ERROR: No matching distribution found for scipy==1.7.1
Requirement already satisfied: pingouin in /usr/local/lib/python3.11/dist-packages (0.5.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from pingouin) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.26.4)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.11/dist-packages (from pingouin) (2.2.2)
Requirement already satisfied: pandas-flavor in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.6.0)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.13.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.14.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (3.2.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.11/dist-packages (from pandas-flavor->pingouin) (2025.1.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels->pingouin) (1.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->pingouin) (1.17.0)

Bibliotecas

In [ ]:
#gerais
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# analises
from scipy import stats as st
import pingouin as pg

Dados

In [ ]:
# dados
dados_ab = pd.read_csv('exampleDataABtest.csv')
dados_ab.head()

  group                 time  clickedTrue
0     A  2016-06-02 02:17:53            0
1     A  2016-06-02 03:03:54            0
2     A  2016-06-02 03:18:56            1
3     B  2016-06-02 03:23:43            0
4     A  2016-06-02 04:04:00            0

In [ ]:
dados_nps = pd.read_csv('nps_example.csv', sep = ';')
dados_nps.head()

,id,response_status,how_long_listening,age,nps_score,gender
0,11706300,Complete,Less than 6 months,25-34,10.0,Female
1,11706302,Complete,1 year to less than 3 years,25-34,10.0,Female
2,11706307,Complete,6 months to less than a year,35-44,10.0,Female
3,11706312,Complete,Less than 6 months,35-44,10.0,Female
4,11706316,Complete,6 months to less than a year,25-34,10.0,Male

Teste T

comparar os grupos

In [ ]:
# estatísticas por grupo
dados_ab.groupby('group') \
        .agg(media_cliques = pd.NamedAgg('clickedTrue', 'mean'),#media (coluna, a funcao que queremos usar = mean media)
             dp_cliques = pd.NamedAgg('clickedTrue', 'std'),#desvio padrao = std
             n = pd.NamedAgg('clickedTrue', 'count')) #count

       media_cliques  dp_cliques    n
group
A               0.04    0.196155  500
B               0.08    0.271565  500

In [ ]:
# dividir os grupos
grA = dados_ab[dados_ab['group'] == 'A']['clickedTrue'] #separamos o grupo A e coluna clicked e gravando na váriavel grA
grB = dados_ab[dados_ab['group'] == 'B']['clickedTrue']

In [ ]:
# aplicar o teste
st.ttest_ind(a=grA, b=grB, alternative='two-sided') #st status tteste_ind teste t

TtestResult(statistic=-2.669938469060931, pvalue=0.007709783987515947, df=998.0)

In [ ]:
# se o p-value < 0,05 - então rejeito a hipótese nula

Usando o Pingouin

In [ ]:
# teste t USANDO PINGOUIN
pg.ttest(x=grA,
         y=grB,
         alternative='two-sided', #grupo A e diferente de B
         confidence = 0.95)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-2.669938,998,two-sided,0.00771,"[-0.07, -0.01]",0.168862,2.349,0.760344

In [ ]:
# se o p-value < 0,05 - então rejeito a hipótese nula A foi diferente de B = B teve maior performace

Teste F

In [ ]:
#perfil das respostas
dados_nps.groupby('response_status') \
  .size()\
  .to_frame('n')\
  .reset_index()

  response_status     n
0        Complete  2281
1      Incomplete   265
2      Terminated    33

In [ ]:
# verificar nulos
dados_nps[dados_nps['nps_score'].isnull()] #isnull existe algum null?

,id,response_status,how_long_listening,age,nps_score,gender
17,11706467,Incomplete,Less than 6 months,18-24,NaN,NaN
31,11706938,Incomplete,1 year to less than 3 years,25-34,NaN,NaN
32,11706979,Incomplete,6 months to less than a year,25-34,NaN,NaN
43,11707426,Incomplete,6 months to less than a year,25-34,NaN,NaN
48,11707719,Incomplete,3 years to less than 5 years,35-44,NaN,NaN
...,...,...,...,...,...,...
2546,13093216,Incomplete,6 months to less than a year,35-44,NaN,NaN
2556,13278063,Incomplete,3 years to less than 5 years,18-24,NaN,NaN
2570,13565327,Complete,1 year to less than 3 years,45-54,NaN,Female
2572,13601847,Incomplete,3 years to less than 5 years,25-34,NaN,NaN
2575,13652344,Incomplete,1 year to less than 3 years,35-44,NaN,NaN

In [ ]:
# filtrar dados
dados_nps_filtrados = dados_nps[(dados_nps['response_status'] == 'Complete') & \ #apenas as pessoas que completou o questionário
  (dados_nps['nps_score'].notna())]

In [ ]:
# resumo dados
dados_nps_filtrados.groupby('age') \ #faixetária
                   .agg(media_nps = pd.NamedAgg('nps_score', 'mean'),
                        dp_nps = pd.NamedAgg('nps_score', 'std'),
                        n = pd.NamedAgg('nps_score', 'size')) \
                   .reset_index()

     age  media_nps    dp_nps    n
0  18-24   9.464539  1.116275  282
1  25-34   9.694828  0.957639  580
2  35-44   9.707612  0.979501  578
3  45-54   9.719039  0.928254  541
4  55-64   9.733871  0.923020  248
5  65-74   9.423077  1.361560   26
6    75+   8.000000  0.000000    2

In [ ]:
# filtrar 75+
dados_nps_filtrados_aj = dados_nps_filtrados[dados_nps_filtrados['age'] != '75+'] #por conta de ter um número de duas pessoas apenas ter respondido não conseguimos usar então ! excluimos essas amostra

Usamos SCIPY

In [ ]:
# separar os grupos
dados_18_24 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '18-24']['nps_score']
dados_25_34 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '25-34']['nps_score']
dados_35_44 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '35-44']['nps_score']
dados_45_54 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '45-54']['nps_score']
dados_55_64 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '55-64']['nps_score']
dados_65_74 = dados_nps_filtrados_aj[dados_nps_filtrados_aj['age'] == '65-74']['nps_score']

In [ ]:
# realizar teste f
st.f_oneway(dados_18_24,
            dados_25_34,
            dados_35_44,
            dados_45_54,
            dados_55_64,
            dados_65_74)

F_onewayResult(statistic=3.5221660981040768, pvalue=0.0035606861304276695)

In [ ]:
# se valor de p < 0,05, rejeitamos a hipótese nula

In [ ]:
# teste f
pg.anova(dv = 'nps_score',
         between = 'age',
         data = dados_nps_filtrados_aj,
         detailed = True)

   Source           SS    DF        MS         F     p-unc      np2
0     age    16.888794     5  3.377759  3.522166  0.003561  0.00777
1  Within  2156.791916  2249  0.959000       NaN       NaN      NaN